### ISSUE TITLE
Question about dual antenna configuration

### ISSUE THREAD

**Issue by Matioupi** [septentrio-gnss/mosaicHAT#1]
Hello,
this picture shows a dual antenna board design, while as far as I know, available Mosaic flavors are single antenna.
Does this mean that a dual antenna version is comming, or that a Mosaic-X5 chip could get a dual antenna firmware version (which would be great).
Regards

**Comment by septentrio-users** [comment]
Dear Mat, indeed Septentrio has on its roadmap a mosaic-H module (dual antenna) which wil be a separate product. The current mosaicHAT deisgn however can be used perfectly with the mosaic-X5 (single antenna). The mosaic-H module will most likely follow the same pin compatibility with the additional 2nd antenna pin. This is preliminary but we know Septentrio will launch this product in the near time.

**Comment by Matioupi** [comment]
Hello, now that the Mosaic H is officially out, I'm re-asking if the design is supporting it ?

**Comment by septentrio-users** [comment]
Hi Mat, yes the design is fully ready for it (will be fully pin compatible and the antenna design done was already thought for that module) but has not been yet tested. mosaic-H is indeed announced now thus dual antenna GNSS in same module form factor which is cool. Surely if you see interest let us know and we can put you in contact with someone at Septentrio to know more about mosaic-H.
