### ISSUE TITLE
Mistake in SPN and DigiKey URL for blue LEDS in BOM

### ISSUE THREAD

**Issue by jgkosh** [septentrio-gnss/mosaicHAT#2]
It looks like item #4 (row 5) for 5 of the blue LEDs lists the wrong SPN and DigiKey URL.  Looking at the neighboring cells, it seems like an appropriate SPN would be:

751-1156-1-ND

and the Digi-Key URL should be:

https://www.digikey.com/en/products/detail/vishay-semiconductor-opto-division/TLMB1100-GS08/1681291

**Comment by Jamalhazem98** [comment]
Thanks jgkosh!
Seems it got the neighbouring TVS diode data by mistake, now it's fixed.
